### ISSUE TITLE
Feature Request: RPC methods for legacy perl interface

### ISSUE THREAD

**Issue by janlazo** [jacquesg/p5-Neovim-Ext#1]
https://github.com/neovim/neovim/pull/11703 allows Neovim to run perl plugins via this perl module but this module is missing the RPC methods required for `if_perl` interface. neovim has all the pieces required to run `:perl` on its end so I need only the RPC methods (ie. `perl_execute`) from this module on a session ([perl-client](https://github.com/jacquesg/p5-Neovim-Ext/blob/b5b7513ec1e22171d7c3596d7ba33fba86fbb444/lib/Neovim/Ext/MsgPack/RPC.pm#L47)), a host ([perl-rplugin-host](https://github.com/jacquesg/p5-Neovim-Ext/blob/master/lib/Neovim/Ext/Plugin/Host.pm#L158)), or a "backend" plugin for some host like the ruby provider. I can handle the rest.

Examples from other providers:
- python: https://github.com/neovim/pynvim/blob/master/pynvim/plugin/script_host.py
- ruby: https://github.com/neovim/neovim-ruby/blob/master/lib/neovim/ruby_provider.rb

**Comment by jacquesg** [comment]
Ok, let me see what I can do, hopefully I will get round to it this week.

**Comment by janlazo** [comment]
@jacquesg What's the status of this ticket?

**Comment by jacquesg** [comment]
@janlazo Finally got round to finishing this up.The latest version on CPAN now has the required changes https://metacpan.org/release/JACQUESG/Neovim-Ext-0.03

I've opened up a PR in Neovim to add [support](https://github.com/neovim/neovim/pull/12809).
