### ISSUE TITLE
Wrong column index for $curwin->Cursor with wide characters

### ISSUE THREAD

**Issue by kurkale6ka** [jacquesg/p5-Neovim-Ext#2]
I tested with a 1 line buffer with these 3 characters only:

a漢a

$curwin->Cursor yields
(1,0) (1,1) and wrongly (1,4) instead of (1,2)

**Comment by jacquesg** [comment]
Hi,

You will need to give a bit more information.

**Comment by jacquesg** [comment]
This may be what you're referring to: https://github.com/neovim/neovim/issues/12973

**Comment by kurkale6ka** [comment]
Thanks, that's it, I didn't know about that issue
