### ISSUE TITLE
Any recommendations how to make it work?

### ISSUE THREAD

**Issue by unclechu** [jacquesg/p5-Neovim-Ext#3]
`:checkhealth` in Neovim 0.5.0 shows me that everything is fine with Perl integration:

``` markdown
## Perl provider (optional)
  - INFO: perl executable: /nix/store/xwqsqp6clmd6z9l91ajqzd57qqlkp2gl-perl-for-neovim/bin/perl
  - OK: Latest "Neovim::Ext" cpan module is installed: 0.05
```

But when I type `:perl whatever` or `:perldo whatever` or `:perlfile whatever` nothing happens, no errors reported. Any thoughts why? It doesn’t matter what the arguments are. I could type something correct like `:perl print "hi"` or `:perl VIM::Msg("hi")`, no effect. :shrug:

**Comment by jacquesg** [comment]
I'm unable to reproduce this. Just installed it from scratch, and running `:perl print "hi"` works out of the box?

**Comment by jacquesg** [comment]
Could you provide the version of perl you're using?

**Comment by unclechu** [comment]
@jacquesg 

```
:!perl --version

This is perl 5, version 34, subversion 1 (v5.34.1) built for x86_64-linux-thread-multi

Copyright 1987-2022, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by unclechu** [comment]
```
:ver
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/0vjynr1jdnvqpy9rcc2kh0agsdgdbzn0-neovim-unwrapped-0.7.0/share/nvim"

Run :checkhealth for more info
```

**Comment by unclechu** [comment]
```
## Perl provider (optional)
  - INFO: perl executable: /nix/store/wpj9v8r87s3s4fy7jynk6lwfd675vi6m-perl-for-neovim/bin/perl
  - OK: Latest "Neovim::Ext" cpan module is installed: 0.05
```

**Comment by unclechu** [comment]
``` console
$ /nix/store/wpj9v8r87s3s4fy7jynk6lwfd675vi6m-perl-for-neovim/bin/perl -e 'print "hi\n"'
hi
```

**Comment by jacquesg** [comment]
Please run `:perl print "hi"` inside of neovim to see the provider working.

**Comment by unclechu** [comment]
@jacquesg 

Typed:
![2022-06-06 15-29-40](https://user-images.githubusercontent.com/799353/172160949-165f6e51-5b4e-46ff-bd86-f2935510c7ea.png)

Pressed Enter:
![2022-06-06 15-29-46](https://user-images.githubusercontent.com/799353/172160974-26caa0cc-7b6b-4e09-bb44-d802c8ca0293.png)

Nothing happens.

**Comment by unclechu** [comment]
Why did you close the issue?

**Comment by unclechu** [comment]
Just for a comparison:

![2022-06-06 15-31-41](https://user-images.githubusercontent.com/799353/172161230-ede9b536-da47-4348-9f6e-8791c7794eb6.png)

![2022-06-06 15-31-46](https://user-images.githubusercontent.com/799353/172161235-9d6213f2-8baf-4a77-852d-5bd8bd8501a9.png)

**Comment by unclechu** [comment]
> Please run :perl print "hi" inside of neovim to see the provider working.

So I did, from the start. It doesn’t work.

**Comment by jacquesg** [comment]
Your issue is configuration related. I've tested with numerous versions of neovim and perl, and I simply cannot reproduce it.

I believe the problem is your configuration.

Careful reminder to be polite...

**Comment by unclechu** [comment]
I’ll try to come up with a minimal repro.

**Comment by unclechu** [comment]
@jacquesg I managed to fix it with https://github.com/unclechu/neovimrc/commit/436b755a9d7d9433a2b446c5c75a9b256847222d in my config by adding explicit dependencies `EvalSafe` and `MsgPackRaw`. I expected them to propagate from `NeovimExt` but it seems they didn’t for some reason.

**Comment by unclechu** [comment]
Problem solved.
