### ISSUE TITLE
$NVIM_LISTEN_ADDRESS will be removed

### ISSUE THREAD

**Issue by justinmk** [jacquesg/p5-Neovim-Ext#4]
I don't see $NVIM_LISTEN_ADDRESS being used in this repo but just a heads up.

https://github.com/neovim/neovim/pull/11009 (Nvim 0.8+) will change Nvim so that $NVIM_LISTEN_ADDRESS is _not_ passed to child processes.  After that, the correct way to detect a "host" or "parent" Nvim is to check for $NVIM env var: this means the current process is a child of Nvim.

The old $NVIM_LISTEN_ADDRESS env var had conflicting purposes as both a parameter ("the current process should _listen on_ this address") and a descriptor ("the current process is a _child of_ this address").

Related change in Nvim node-client: https://github.com/neovim/node-client/pull/195

**Comment by jacquesg** [comment]
Thank you for the report. We used this to tell Nvim to listen on a socket, but now using `--listen`. Fixed by 754e0e759251f6c25449c0318a1f399a8db5d43b
